<?php

namespace AppBundle\Repository;

/**
 * ToListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToListRepository extends \Doctrine\ORM\EntityRepository
{
}
